### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Ravin890** [RootsTeam/Animunda#1]
Tried to run using forge 2125, 2117, and 2099 and all experienced the same crash. 
[crash-2016-11-15_23.12.00-server.txt](https://github.com/RootsTeam/Animunda/files/595295/crash-2016-11-15_23.12.00-server.txt)

**Comment by ShadowGamerXY** [comment]
Fixed!

**Comment by Ravin890** [comment]
Recent file for quick test on server :D
[crash-2016-12-16_13.29.11-server.txt](https://github.com/RootsTeam/Animunda/files/657954/crash-2016-12-16_13.29.11-server.txt)
