### ISSUE TITLE
Icicle Drop ice cube spam in world

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Animunda#10]
Can the ice cubes that fall off the sides despawn faster than they currently do without affecting vanilla minecraft? If I use Icicle a few times there is a lot of loose Ice blocks all over the ground around it. I have to say I love how it looks with those around it though. If this is as intended then please just close this. :)

**Comment by ShadowGamerXY** [comment]
It meant to do that.. I will look if I can somehow make it a less time to despawn .
