### ISSUE TITLE
Internal Server Error when Crafting Void Pickaxe on a Server

### ISSUE THREAD

**Issue by kingofrunes** [RootsTeam/Animunda#14]
Whenever I try crafting the void pickaxe on a server, it causes the client to give an Internal Server Error that prevents me from being able to login.

9.12 10:23:42 [Server] INFO Caused by: java.lang.NullPointerException
29.12 10:23:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
29.12 10:23:42 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
29.12 10:23:42 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
29.12 10:23:42 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
29.12 10:23:42 [Server] INFO net.minecraft.util.ReportedException: Ticking player
29.12 10:23:42 [Server] Server thread/WARN Failed to handle packet

However, if I grab the one from JEI it works just fine. Upon closer inspection with an nbt editor the only difference between the one you craft and the one that JEI generates is that the JEI one has an extra tag: 0 entries in it.
http://puu.sh/t4Ttb/d0a7ffbdc2.png

Any particular reason why this is happening? This issue does not appear to happen in single player mode.

**Comment by ShadowGamerXY** [comment]
Should be fixed in the next update! Please reopen this issue if it crashes after you update to the newest version when it comes out.
